import os
import json
import google.generativeai as genai
# We import as 'YTA' to prevent any naming conflicts
from youtube_transcript_api import YouTubeTranscriptApi as YTA
from youtube_transcript_api import TranscriptsDisabled, NoTranscriptFound
from flask import Flask, render_template, request, jsonify

app = Flask(__name__)

# --- CONFIGURATION ---
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY") 
STRIPE_LINK = os.environ.get("STRIPE_LINK", "#") 

if GEMINI_API_KEY:
    genai.configure(api_key=GEMINI_API_KEY)

def get_video_id(url):
    """Extracts video ID from a YouTube URL"""
    if "v=" in url:
        return url.split("v=")[1].split("&")[0]
    elif "youtu.be/" in url:
        return url.split("youtu.be/")[1].split("?")[0]
    return None

def generate_viral_content(transcript_text):
    if not GEMINI_API_KEY:
        return {"error": "API Key missing"}
    
    model = genai.GenerativeModel('gemini-1.5-flash')
    
    prompt = f"""
    You are a viral content strategist for B2B founders. Analyze this YouTube transcript.
    
    Return a pure JSON response with exactly these fields:
    {{
        "score": (integer 0-100 based on viral potential),
        "verdict": (a punchy, slightly controversial 1-sentence opinion),
        "linkedin_post": (A highly engaging LinkedIn post with a 'Hook', 'Body', and 'Call to Action'. Use short lines. No hashtags.)
    }}

    Transcript:
    {transcript_text[:12000]}
    """
    
    try:
        response = model.generate_content(prompt)
        clean_text = response.text.replace("```json", "").replace("```", "").strip()
        data = json.loads(clean_text)
        
        # Watermark
        watermark = "\n\nPS: I generated this post in 10 seconds using ContentEngine. 🚀"
        data['linkedin_post'] += watermark
        
        return data
    except Exception as e:
        return {
            "score": 88,
            "verdict": "Great insights, highly repurposable.",
            "linkedin_post": response.text + "\n\n(Generated by ContentEngine)"
        }

@app.route('/')
def home():
    return render_template('index.html', stripe_link=STRIPE_LINK)

@app.route('/generate', methods=['POST'])
def generate():
    data = request.json
    video_url = data.get('url')
    
    if not video_url:
        return jsonify({"error": "No URL provided"}), 400

    video_id = get_video_id(video_url)
    if not video_id:
        return jsonify({"error": "Invalid YouTube URL"}), 400

    try:
        # UPDATED LINE: Using the alias 'YTA' to avoid namespace errors
        transcript_list = YTA.get_transcript(video_id)
        transcript_text = " ".join([t['text'] for t in transcript_list])
        
        result = generate_viral_content(transcript_text)
        return jsonify(result)

    except (TranscriptsDisabled, NoTranscriptFound):
        return jsonify({"error": "No captions available for this video."}), 400
    except Exception as e:
        return jsonify({"error": str(e)}), 500

if __name__ == '__main__':
    port = int(os.environ.get("PORT", 10000))
    app.run(host='0.0.0.0', port=port)