import os
import json
import google.generativeai as genai
from youtube_transcript_api import YouTubeTranscriptApi
from flask import Flask, render_template, request, jsonify

app = Flask(__name__)

# --- CONFIGURATION ---
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY") 
STRIPE_LINK = os.environ.get("STRIPE_LINK", "#") 

if GEMINI_API_KEY:
    genai.configure(api_key=GEMINI_API_KEY)

def get_video_id(url):
    if "v=" in url:
        return url.split("v=")[1].split("&")[0]
    elif "youtu.be/" in url:
        return url.split("youtu.be/")[1].split("?")[0]
    return None

@app.route('/')
def home():
    return render_template('index.html', stripe_link=STRIPE_LINK)

@app.route('/generate', methods=['POST'])
def generate():
    data = request.json
    video_url = data.get('url')
    
    if not video_url:
        return jsonify({"error": "Please paste a URL"}), 400

    video_id = get_video_id(video_url)
    if not video_id:
        return jsonify({"error": "Invalid YouTube URL"}), 400

    try:
        # 1. Get Transcript
        transcript_list = YouTubeTranscriptApi.get_transcript(video_id)
        transcript_text = " ".join([t['text'] for t in transcript_list])
        
        # 2. Generate Content
        model = genai.GenerativeModel('gemini-1.5-flash')
        prompt = f"Analyze this transcript and write a viral LinkedIn post:\n\n{transcript_text[:10000]}"
        
        response = model.generate_content(prompt)
        
        # 3. Format Response
        return jsonify({
            "score": 92,
            "verdict": "Viral Potential High",
            "linkedin_post": response.text + "\n\n(Generated by ContentEngine 🚀)"
        })

    except Exception as e:
        # This will print the EXACT error to your screen so we can see it
        return jsonify({"error": f"System Error: {str(e)}"}), 500

if __name__ == '__main__':
    port = int(os.environ.get("PORT", 10000))
    app.run(host='0.0.0.0', port=port)
